-- Least-privilege service roles. No users or privileged administrative roles are
-- assigned here; human/service identity assignment is an explicit deployment step.

CREATE ROLE IF NOT EXISTS SPOTIFY_LOADER
  COMMENT = 'Owns Snowpipe loading duties limited to LANDING';
CREATE ROLE IF NOT EXISTS SPOTIFY_TRANSFORMER
  COMMENT = 'Runs dbt transformations across STAGING, CORE, and MARTS';
CREATE ROLE IF NOT EXISTS SPOTIFY_ANALYST
  COMMENT = 'Read-only MARTS access for BI consumers';

-- Common database visibility.
GRANT USAGE ON DATABASE SPOTIFY_ANALYTICS TO ROLE SPOTIFY_LOADER;
GRANT USAGE ON DATABASE SPOTIFY_ANALYTICS TO ROLE SPOTIFY_TRANSFORMER;
GRANT USAGE ON DATABASE SPOTIFY_ANALYTICS TO ROLE SPOTIFY_ANALYST;

-- Loader: serverless Snowpipe duties only. No virtual warehouse usage is needed.
GRANT USAGE ON SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_LOADER;
GRANT CREATE PIPE ON SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_LOADER;
GRANT INSERT ON ALL TABLES IN SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_LOADER;

-- Transformer: read Landing, create analytical relations, and use bounded compute.
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SPOTIFY_TRANSFORMER;
GRANT USAGE ON SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_TRANSFORMER;

GRANT USAGE ON SCHEMA SPOTIFY_ANALYTICS.STAGING TO ROLE SPOTIFY_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SPOTIFY_ANALYTICS.STAGING TO ROLE SPOTIFY_TRANSFORMER;
GRANT USAGE ON SCHEMA SPOTIFY_ANALYTICS.CORE TO ROLE SPOTIFY_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SPOTIFY_ANALYTICS.CORE TO ROLE SPOTIFY_TRANSFORMER;
GRANT USAGE ON SCHEMA SPOTIFY_ANALYTICS.MARTS TO ROLE SPOTIFY_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SPOTIFY_ANALYTICS.MARTS TO ROLE SPOTIFY_TRANSFORMER;

-- Analyst: MARTS only, intentionally excluding Landing/Staging/Core.
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SPOTIFY_ANALYST;
GRANT USAGE ON SCHEMA SPOTIFY_ANALYTICS.MARTS TO ROLE SPOTIFY_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SPOTIFY_ANALYTICS.MARTS TO ROLE SPOTIFY_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_ANALYTICS.MARTS TO ROLE SPOTIFY_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SPOTIFY_ANALYTICS.MARTS TO ROLE SPOTIFY_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SPOTIFY_ANALYTICS.MARTS TO ROLE SPOTIFY_ANALYST;
