CREATE FILE FORMAT IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.PARQUET_FORMAT
  TYPE = PARQUET
  COMPRESSION = SNAPPY
  BINARY_AS_TEXT = FALSE
  USE_LOGICAL_TYPE = TRUE
  USE_VECTORIZED_SCANNER = TRUE
  COMMENT = 'Spark 3.5.6 Snappy Parquet written by M3 Silver curation';

GRANT USAGE ON FILE FORMAT SPOTIFY_ANALYTICS.LANDING.PARQUET_FORMAT TO ROLE SPOTIFY_LOADER;
