-- Landing tables mirror the M3 Silver Parquet contract exactly, then append load-audit
-- metadata. No business transformations or surrogate keys belong in this layer.

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_ARTISTS (
  ARTIST_ID VARCHAR NOT NULL,
  ARTIST_NAME VARCHAR NOT NULL,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR NOT NULL,
  _FILE_ROW_NUMBER NUMBER(38, 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_ALBUMS (
  ALBUM_ID VARCHAR NOT NULL,
  ALBUM_NAME VARCHAR NOT NULL,
  ALBUM_TYPE VARCHAR,
  RELEASE_DATE VARCHAR,
  TOTAL_TRACKS NUMBER(38, 0),
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR NOT NULL,
  _FILE_ROW_NUMBER NUMBER(38, 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_TRACKS (
  TRACK_ID VARCHAR NOT NULL,
  TRACK_NAME VARCHAR NOT NULL,
  ALBUM_ID VARCHAR,
  DURATION_MS NUMBER(38, 0) NOT NULL,
  IS_EXPLICIT BOOLEAN NOT NULL,
  IS_LOCAL BOOLEAN NOT NULL,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR NOT NULL,
  _FILE_ROW_NUMBER NUMBER(38, 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_TRACK_ARTISTS (
  TRACK_ID VARCHAR NOT NULL,
  ARTIST_ID VARCHAR NOT NULL,
  ARTIST_ORDER NUMBER(38, 0) NOT NULL,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR NOT NULL,
  _FILE_ROW_NUMBER NUMBER(38, 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS (
  PLAYLIST_ID VARCHAR NOT NULL,
  SPOTIFY_SNAPSHOT_ID VARCHAR NOT NULL,
  PLAYLIST_NAME VARCHAR NOT NULL,
  TRACK_ID VARCHAR NOT NULL,
  TRACK_POSITION NUMBER(38, 0) NOT NULL,
  ADDED_AT TIMESTAMP_NTZ,
  SNAPSHOT_DATE DATE NOT NULL,
  SNAPSHOT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
  PIPELINE_RUN_ID VARCHAR NOT NULL,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR NOT NULL,
  _FILE_ROW_NUMBER NUMBER(38, 0) NOT NULL
);
