-- Landing tables mirror the M3 Silver Parquet contract exactly, then append load-audit
-- metadata. No business transformations or surrogate keys belong in this layer.

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_ARTISTS (
  ARTIST_ID VARCHAR(64) NOT NULL,
  ARTIST_NAME VARCHAR(255) NOT NULL,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR(512) NOT NULL,
  _FILE_ROW_NUMBER INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_ALBUMS (
  ALBUM_ID VARCHAR(64) NOT NULL,
  ALBUM_NAME VARCHAR(255) NOT NULL,
  ALBUM_TYPE VARCHAR(32),
  RELEASE_DATE VARCHAR(16),
  TOTAL_TRACKS INTEGER,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR(512) NOT NULL,
  _FILE_ROW_NUMBER INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_TRACKS (
  TRACK_ID VARCHAR(64) NOT NULL,
  TRACK_NAME VARCHAR(255) NOT NULL,
  ALBUM_ID VARCHAR(64),
  DURATION_MS INTEGER NOT NULL,
  IS_EXPLICIT BOOLEAN NOT NULL,
  IS_LOCAL BOOLEAN NOT NULL,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR(512) NOT NULL,
  _FILE_ROW_NUMBER INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_TRACK_ARTISTS (
  TRACK_ID VARCHAR(64) NOT NULL,
  ARTIST_ID VARCHAR(64) NOT NULL,
  ARTIST_ORDER INTEGER NOT NULL,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR(512) NOT NULL,
  _FILE_ROW_NUMBER INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS (
  PLAYLIST_ID VARCHAR(64) NOT NULL,
  SPOTIFY_SNAPSHOT_ID VARCHAR(128) NOT NULL,
  PLAYLIST_NAME VARCHAR(255) NOT NULL,
  TRACK_ID VARCHAR(64) NOT NULL,
  TRACK_POSITION INTEGER NOT NULL,
  ADDED_AT TIMESTAMP_NTZ,
  SNAPSHOT_DATE DATE NOT NULL,
  SNAPSHOT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
  PIPELINE_RUN_ID VARCHAR(64) NOT NULL,
  INGESTION_DATE DATE NOT NULL,
  _LOADED_AT TIMESTAMP_NTZ NOT NULL,
  _FILE_NAME VARCHAR(512) NOT NULL,
  _FILE_ROW_NUMBER INTEGER NOT NULL
);
