-- Snowpipe definitions are versioned here but not executed in this offline round.
-- M8 will wire S3 object-created notifications to each pipe's Snowflake-managed SQS
-- notification channel. Snowpipe file tracking is transport idempotency only; canonical
-- business/retry deduplication remains the dbt responsibility at the daily snapshot grain.

-- Snowflake requires SELECT and INSERT on the target table for pipe creation/execution.
GRANT SELECT ON ALL TABLES IN SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_LOADER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_ANALYTICS.LANDING TO ROLE SPOTIFY_LOADER;

CREATE PIPE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.PIPE_LANDING_ARTISTS
  AUTO_INGEST = TRUE
  COMMENT = 'Load Silver artists Parquet into Landing'
  AS
  COPY INTO SPOTIFY_ANALYTICS.LANDING.LANDING_ARTISTS (
    ARTIST_ID, ARTIST_NAME, INGESTION_DATE, _LOADED_AT, _FILE_NAME, _FILE_ROW_NUMBER
  )
  FROM (
    SELECT
      T.$1:artist_id::VARCHAR(64),
      T.$1:artist_name::VARCHAR(255),
      T.$1:ingestion_date::DATE,
      CONVERT_TIMEZONE('UTC', METADATA$START_SCAN_TIME)::TIMESTAMP_NTZ,
      METADATA$FILENAME::VARCHAR(512),
      METADATA$FILE_ROW_NUMBER::INTEGER
    FROM @SPOTIFY_ANALYTICS.LANDING.SILVER_STAGE/artists/
      (FILE_FORMAT => 'SPOTIFY_ANALYTICS.LANDING.PARQUET_FORMAT') T
  )
  ON_ERROR = SKIP_FILE;

CREATE PIPE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.PIPE_LANDING_ALBUMS
  AUTO_INGEST = TRUE
  COMMENT = 'Load Silver albums Parquet into Landing'
  AS
  COPY INTO SPOTIFY_ANALYTICS.LANDING.LANDING_ALBUMS (
    ALBUM_ID, ALBUM_NAME, ALBUM_TYPE, RELEASE_DATE, TOTAL_TRACKS, INGESTION_DATE,
    _LOADED_AT, _FILE_NAME, _FILE_ROW_NUMBER
  )
  FROM (
    SELECT
      T.$1:album_id::VARCHAR(64),
      T.$1:album_name::VARCHAR(255),
      T.$1:album_type::VARCHAR(32),
      T.$1:release_date::VARCHAR(16),
      T.$1:total_tracks::INTEGER,
      T.$1:ingestion_date::DATE,
      CONVERT_TIMEZONE('UTC', METADATA$START_SCAN_TIME)::TIMESTAMP_NTZ,
      METADATA$FILENAME::VARCHAR(512),
      METADATA$FILE_ROW_NUMBER::INTEGER
    FROM @SPOTIFY_ANALYTICS.LANDING.SILVER_STAGE/albums/
      (FILE_FORMAT => 'SPOTIFY_ANALYTICS.LANDING.PARQUET_FORMAT') T
  )
  ON_ERROR = SKIP_FILE;

CREATE PIPE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.PIPE_LANDING_TRACKS
  AUTO_INGEST = TRUE
  COMMENT = 'Load Silver tracks Parquet into Landing'
  AS
  COPY INTO SPOTIFY_ANALYTICS.LANDING.LANDING_TRACKS (
    TRACK_ID, TRACK_NAME, ALBUM_ID, DURATION_MS, IS_EXPLICIT, IS_LOCAL, INGESTION_DATE,
    _LOADED_AT, _FILE_NAME, _FILE_ROW_NUMBER
  )
  FROM (
    SELECT
      T.$1:track_id::VARCHAR(64),
      T.$1:track_name::VARCHAR(255),
      T.$1:album_id::VARCHAR(64),
      T.$1:duration_ms::INTEGER,
      T.$1:is_explicit::BOOLEAN,
      T.$1:is_local::BOOLEAN,
      T.$1:ingestion_date::DATE,
      CONVERT_TIMEZONE('UTC', METADATA$START_SCAN_TIME)::TIMESTAMP_NTZ,
      METADATA$FILENAME::VARCHAR(512),
      METADATA$FILE_ROW_NUMBER::INTEGER
    FROM @SPOTIFY_ANALYTICS.LANDING.SILVER_STAGE/tracks/
      (FILE_FORMAT => 'SPOTIFY_ANALYTICS.LANDING.PARQUET_FORMAT') T
  )
  ON_ERROR = SKIP_FILE;

CREATE PIPE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.PIPE_LANDING_TRACK_ARTISTS
  AUTO_INGEST = TRUE
  COMMENT = 'Load Silver track-artist bridge Parquet into Landing'
  AS
  COPY INTO SPOTIFY_ANALYTICS.LANDING.LANDING_TRACK_ARTISTS (
    TRACK_ID, ARTIST_ID, ARTIST_ORDER, INGESTION_DATE,
    _LOADED_AT, _FILE_NAME, _FILE_ROW_NUMBER
  )
  FROM (
    SELECT
      T.$1:track_id::VARCHAR(64),
      T.$1:artist_id::VARCHAR(64),
      T.$1:artist_order::INTEGER,
      T.$1:ingestion_date::DATE,
      CONVERT_TIMEZONE('UTC', METADATA$START_SCAN_TIME)::TIMESTAMP_NTZ,
      METADATA$FILENAME::VARCHAR(512),
      METADATA$FILE_ROW_NUMBER::INTEGER
    FROM @SPOTIFY_ANALYTICS.LANDING.SILVER_STAGE/track_artists/
      (FILE_FORMAT => 'SPOTIFY_ANALYTICS.LANDING.PARQUET_FORMAT') T
  )
  ON_ERROR = SKIP_FILE;

CREATE PIPE IF NOT EXISTS SPOTIFY_ANALYTICS.LANDING.PIPE_LANDING_PLAYLIST_SNAPSHOTS
  AUTO_INGEST = TRUE
  COMMENT = 'Load Silver historical playlist-slot Parquet into Landing'
  AS
  COPY INTO SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS (
    PLAYLIST_ID, SPOTIFY_SNAPSHOT_ID, PLAYLIST_NAME, TRACK_ID, TRACK_POSITION, ADDED_AT,
    SNAPSHOT_DATE, SNAPSHOT_TIMESTAMP, PIPELINE_RUN_ID, INGESTION_DATE,
    _LOADED_AT, _FILE_NAME, _FILE_ROW_NUMBER
  )
  FROM (
    SELECT
      T.$1:playlist_id::VARCHAR(64),
      T.$1:spotify_snapshot_id::VARCHAR(128),
      T.$1:playlist_name::VARCHAR(255),
      T.$1:track_id::VARCHAR(64),
      T.$1:track_position::INTEGER,
      CONVERT_TIMEZONE('UTC', T.$1:added_at::TIMESTAMP_LTZ)::TIMESTAMP_NTZ,
      T.$1:snapshot_date::DATE,
      CONVERT_TIMEZONE('UTC', T.$1:snapshot_timestamp::TIMESTAMP_LTZ)::TIMESTAMP_NTZ,
      T.$1:pipeline_run_id::VARCHAR(64),
      T.$1:ingestion_date::DATE,
      CONVERT_TIMEZONE('UTC', METADATA$START_SCAN_TIME)::TIMESTAMP_NTZ,
      METADATA$FILENAME::VARCHAR(512),
      METADATA$FILE_ROW_NUMBER::INTEGER
    FROM @SPOTIFY_ANALYTICS.LANDING.SILVER_STAGE/playlist_snapshots/
      (FILE_FORMAT => 'SPOTIFY_ANALYTICS.LANDING.PARQUET_FORMAT') T
  )
  ON_ERROR = SKIP_FILE;
