-- Read-only operator queries for the later live validation phase.
-- They intentionally use Information Schema COPY_HISTORY because it includes Snowpipe.

-- 1. Current Landing row counts by physical ingestion partition.
SELECT 'LANDING_ARTISTS' AS TABLE_NAME, INGESTION_DATE, COUNT(*) AS ROW_COUNT
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_ARTISTS GROUP BY INGESTION_DATE
UNION ALL
SELECT 'LANDING_ALBUMS', INGESTION_DATE, COUNT(*)
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_ALBUMS GROUP BY INGESTION_DATE
UNION ALL
SELECT 'LANDING_TRACKS', INGESTION_DATE, COUNT(*)
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_TRACKS GROUP BY INGESTION_DATE
UNION ALL
SELECT 'LANDING_TRACK_ARTISTS', INGESTION_DATE, COUNT(*)
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_TRACK_ARTISTS GROUP BY INGESTION_DATE
UNION ALL
SELECT 'LANDING_PLAYLIST_SNAPSHOTS', INGESTION_DATE, COUNT(*)
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS GROUP BY INGESTION_DATE
ORDER BY INGESTION_DATE DESC, TABLE_NAME;

-- 2. Snowpipe load health for the last 24 hours. Nonzero ERROR_COUNT, non-Loaded
-- status, or ROW_PARSED > ROW_COUNT requires operator review before dbt proceeds.
WITH COPY_EVENTS AS (
  SELECT * FROM TABLE(SPOTIFY_ANALYTICS.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'SPOTIFY_ANALYTICS.LANDING.LANDING_ARTISTS',
    START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
  ))
  UNION ALL
  SELECT * FROM TABLE(SPOTIFY_ANALYTICS.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'SPOTIFY_ANALYTICS.LANDING.LANDING_ALBUMS',
    START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
  ))
  UNION ALL
  SELECT * FROM TABLE(SPOTIFY_ANALYTICS.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'SPOTIFY_ANALYTICS.LANDING.LANDING_TRACKS',
    START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
  ))
  UNION ALL
  SELECT * FROM TABLE(SPOTIFY_ANALYTICS.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'SPOTIFY_ANALYTICS.LANDING.LANDING_TRACK_ARTISTS',
    START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
  ))
  UNION ALL
  SELECT * FROM TABLE(SPOTIFY_ANALYTICS.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS',
    START_TIME => DATEADD('hour', -24, CURRENT_TIMESTAMP())
  ))
)
SELECT
  TABLE_NAME,
  PIPE_NAME,
  FILE_NAME,
  STATUS,
  ROW_PARSED,
  ROW_COUNT,
  ROW_PARSED - ROW_COUNT AS REJECTED_ROWS,
  ERROR_COUNT,
  FIRST_ERROR_MESSAGE,
  PIPE_RECEIVED_TIME,
  LAST_LOAD_TIME,
  DATEDIFF('second', PIPE_RECEIVED_TIME, LAST_LOAD_TIME) AS LOAD_LATENCY_SECONDS,
  BYTES_BILLED
FROM COPY_EVENTS
ORDER BY LAST_LOAD_TIME DESC;

-- 3. Duplicate physical file rows indicate a broken ingestion/load contract.
SELECT _FILE_NAME, _FILE_ROW_NUMBER, COUNT(*) AS DUPLICATE_COUNT
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS
GROUP BY _FILE_NAME, _FILE_ROW_NUMBER
HAVING COUNT(*) > 1;

-- 4. Canonical analytical grain violations. Physical retry rows may exist in Landing,
-- so include the source version/run metadata in diagnostics; dbt resolves retries later.
SELECT
  PLAYLIST_ID,
  SNAPSHOT_DATE,
  TRACK_POSITION,
  COUNT(*) AS PHYSICAL_ROWS,
  COUNT(DISTINCT SPOTIFY_SNAPSHOT_ID) AS SOURCE_VERSIONS,
  COUNT(DISTINCT PIPELINE_RUN_ID) AS PIPELINE_RUNS
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS
GROUP BY PLAYLIST_ID, SNAPSHOT_DATE, TRACK_POSITION
HAVING COUNT(*) > 1;

-- 5. Hive partition path and embedded ingestion_date must agree.
SELECT _FILE_NAME, INGESTION_DATE
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS
WHERE TRY_TO_DATE(
  REGEXP_SUBSTR(_FILE_NAME, 'ingestion_date=([0-9]{4}-[0-9]{2}-[0-9]{2})', 1, 1, 'e', 1)
) IS DISTINCT FROM INGESTION_DATE;

-- 6. Required-key/null sanity checks across Landing.
SELECT 'ARTISTS' AS DATASET, COUNT(*) AS INVALID_ROWS
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_ARTISTS
WHERE ARTIST_ID IS NULL OR ARTIST_NAME IS NULL OR INGESTION_DATE IS NULL
UNION ALL
SELECT 'ALBUMS', COUNT(*)
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_ALBUMS
WHERE ALBUM_ID IS NULL OR ALBUM_NAME IS NULL OR INGESTION_DATE IS NULL
UNION ALL
SELECT 'TRACKS', COUNT(*)
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_TRACKS
WHERE TRACK_ID IS NULL OR TRACK_NAME IS NULL OR DURATION_MS IS NULL OR INGESTION_DATE IS NULL
UNION ALL
SELECT 'TRACK_ARTISTS', COUNT(*)
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_TRACK_ARTISTS
WHERE TRACK_ID IS NULL OR ARTIST_ID IS NULL OR ARTIST_ORDER IS NULL OR INGESTION_DATE IS NULL
UNION ALL
SELECT 'PLAYLIST_SNAPSHOTS', COUNT(*)
FROM SPOTIFY_ANALYTICS.LANDING.LANDING_PLAYLIST_SNAPSHOTS
WHERE PLAYLIST_ID IS NULL OR SPOTIFY_SNAPSHOT_ID IS NULL OR TRACK_ID IS NULL
   OR TRACK_POSITION IS NULL OR SNAPSHOT_DATE IS NULL OR PIPELINE_RUN_ID IS NULL;
